### ISSUE TITLE
spdlog::basic_logger_mt编译错误

### ISSUE THREAD

**Issue by Augusthyq** [chenjianqu/RAFT_Libtorch#2]
非常感谢您的开源代码，我在编译时遇到错误
RAFT_Libtorch/RAFT/src/Config.cpp:48:24: error: ‘basic_logger_mt’ is not a member of ‘spdlog’
   48 |     sgLogger = spdlog::basic_logger_mt("segmentor_log",Config::SEGMENTOR_LOG_PATH);
请问这是为什么呢

**Comment by bromotdi** [comment]
Hi, how did you fix it? )
